services:
  - type: web
    name: ch7-ex-download
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m -Djava.awt.headless=true"
      - key: CATALINA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
